name: Sync to Hugging Face hub
on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Push ONLY Required Files to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_SPACE_DOTSRIVAL_TOKEN }}
        run: |
          mkdir /tmp/deploy
          cp app.py preview.html Dockerfile requirements.txt /tmp/deploy/
          cd /tmp/deploy
          
          # Hugging Face ku thevayana README config file ah create pandrom
          cat << 'EOF' > README.md
          ---
          title: DriveBase
          emoji: 🚀
          colorFrom: blue
          colorTo: indigo
          sdk: docker
          app_port: 7860
          pinned: false
          ---
          EOF
          
          git init
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy to Hugging Face"
          git push --force https://DOTSRIVAL:$HF_TOKEN@huggingface.co/spaces/DOTSRIVAL/reclone master:main
